import turtle as tr
t=tr.Turtle()
t.speed(10)
def circle(x,y,radius,color):
	t.begin_fill()
	t.fillcolor(color)
	t.up()
	t.goto(x,y)
	t.down()
	t.circle(radius)
	t.end_fill()
circle(0,-320,320,"red")
circle(0,-260,260,"white")
circle(0,-200,200,"red")
circle(0,-140,140,"blue")
t.up()
t.home()
t.goto(-130,45)
t.begin_fill()
t.fillcolor("white")
for i in range(5):
	t.fd(260)
	t.rt(144)
t.end_fill()
t.hideturtle()
tr.done()
